// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_ivLQYZuB3pBbOLzWNoNu7H-VXb1LIPE',
    appId: '1:967896713448:web:e870de46000f39fcd8e15d',
    messagingSenderId: '967896713448',
    projectId: 'notifications-plum-apps',
    authDomain: 'notifications-plum-apps.firebaseapp.com',
    storageBucket: 'notifications-plum-apps.firebasestorage.app',
    measurementId: 'G-KF4Q98T890',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCor8qdKl8RY2U9F9zGVpoTOIYIuC9MMm0',
    appId: '1:967896713448:android:ea51fedde35377bcd8e15d',
    messagingSenderId: '967896713448',
    projectId: 'notifications-plum-apps',
    storageBucket: 'notifications-plum-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLHcktwimKN49xTcIuNK_2T2RyYJIR5xE',
    appId: '1:967896713448:ios:b169e3b4d0f22c22d8e15d',
    messagingSenderId: '967896713448',
    projectId: 'notifications-plum-apps',
    storageBucket: 'notifications-plum-apps.firebasestorage.app',
    iosBundleId: 'com.example.servicesApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLHcktwimKN49xTcIuNK_2T2RyYJIR5xE',
    appId: '1:967896713448:ios:b169e3b4d0f22c22d8e15d',
    messagingSenderId: '967896713448',
    projectId: 'notifications-plum-apps',
    storageBucket: 'notifications-plum-apps.firebasestorage.app',
    iosBundleId: 'com.example.servicesApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_ivLQYZuB3pBbOLzWNoNu7H-VXb1LIPE',
    appId: '1:967896713448:web:968ce4828b88ef42d8e15d',
    messagingSenderId: '967896713448',
    projectId: 'notifications-plum-apps',
    authDomain: 'notifications-plum-apps.firebaseapp.com',
    storageBucket: 'notifications-plum-apps.firebasestorage.app',
    measurementId: 'G-ZFCZFX6ZJF',
  );

}